INSERT INTO TIPOENFERMEDAD (IDTIPOENFERMEDAD, NOMBRE, DESCRIPCION) VALUES (1, 'Alergias', 'Enfermedades autoinmunes');
INSERT INTO TIPOENFERMEDAD (IDTIPOENFERMEDAD, NOMBRE, DESCRIPCION) VALUES (2, 'Oncológicos', 'Todos los tipos de cáncer');
INSERT INTO TIPOENFERMEDAD (IDTIPOENFERMEDAD, NOMBRE, DESCRIPCION) VALUES (3, 'Hematológicas', 'Relacionadas a la sangre');
INSERT INTO TIPOENFERMEDAD (IDTIPOENFERMEDAD, NOMBRE, DESCRIPCION) VALUES (4, 'Respiratorio', 'Relacionadas a la vías áreas y pulmones');
INSERT INTO SITUACIONADMINISTRATIVA (IDSITUACIONADMINISTRATIVA, DESCRIPCION) VALUES (1, 'Activo');
INSERT INTO SITUACIONADMINISTRATIVA (IDSITUACIONADMINISTRATIVA, DESCRIPCION) VALUES (2, 'Inactivo');
INSERT INTO DEPARTAMENTO(IDDEPARTAMENTO,NOMBRE)VALUES(1,'Contabilidad');
INSERT INTO DEPARTAMENTO(IDDEPARTAMENTO,NOMBRE)VALUES(2,'Sistemas');
